#!/usr/bin/env node
// Single source of truth for the release version: server/package.json.
// Propagates that version to every other file that carries it.
//
//   node scripts/bump-version.mjs 0.4.0       set explicit version
//   node scripts/bump-version.mjs --bump=minor bump from package.json
//   node scripts/bump-version.mjs --check      verify all sources agree
//   node scripts/bump-version.mjs --dry-run 0.4.0   print diff, write nothing
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SEMVER = /^[0-9]+\.[0-9]+\.[0-9]+$/;
const p = (...s) => path.join(repoRoot, ...s);
const readJson = (file) => JSON.parse(fs.readFileSync(file, "utf8"));

function versionTs(v) {
  return [
    "// Generated by scripts/bump-version.mjs from server/package.json.",
    "// Do not edit by hand — run `node scripts/bump-version.mjs <version>`.",
    `export const VERSION = ${JSON.stringify(v)};`,
    "",
  ].join("\n");
}

const INFO_LUA = /VERSION = \{ major=\d+, minor=\d+, revision=\d+, build=\d+ \}/;

// Each target reads its current version and rewrites it. server/package.json
// is the canonical source — listed first so --check compares against it.
const targets = [
  {
    name: "server/package.json",
    file: p("server", "package.json"),
    read() {
      return readJson(this.file).version;
    },
    write(v) {
      const j = readJson(this.file);
      j.version = v;
      fs.writeFileSync(this.file, JSON.stringify(j, null, 2) + "\n");
    },
  },
  {
    name: "server/package-lock.json",
    file: p("server", "package-lock.json"),
    read() {
      return readJson(this.file).version;
    },
    write(v) {
      const j = readJson(this.file);
      j.version = v;
      if (j.packages?.[""]) j.packages[""].version = v;
      fs.writeFileSync(this.file, JSON.stringify(j, null, 2) + "\n");
    },
  },
  {
    name: "server/src/version.ts",
    file: p("server", "src", "version.ts"),
    read() {
      const m = fs.readFileSync(this.file, "utf8").match(/export const VERSION = "([^"]+)"/);
      return m?.[1] ?? null;
    },
    write(v) {
      fs.writeFileSync(this.file, versionTs(v));
    },
  },
  {
    name: "mcpb/manifest.json",
    file: p("mcpb", "manifest.json"),
    read() {
      return readJson(this.file).version;
    },
    write(v) {
      const j = readJson(this.file);
      j.version = v;
      fs.writeFileSync(this.file, JSON.stringify(j, null, 2) + "\n");
    },
  },
  {
    name: "plugin/LightroomMCP.lrplugin/Info.lua",
    file: p("plugin", "LightroomMCP.lrplugin", "Info.lua"),
    read() {
      const m = fs
        .readFileSync(this.file, "utf8")
        .match(/VERSION = \{ major=(\d+), minor=(\d+), revision=(\d+), build=\d+ \}/);
      return m ? `${m[1]}.${m[2]}.${m[3]}` : null;
    },
    write(v) {
      const [maj, min, pat] = v.split(".");
      const src = fs.readFileSync(this.file, "utf8");
      if (!INFO_LUA.test(src)) throw new Error("Info.lua: VERSION line not found");
      fs.writeFileSync(
        this.file,
        src.replace(INFO_LUA, `VERSION = { major=${maj}, minor=${min}, revision=${pat}, build=0 }`),
      );
    },
  },
];

function fail(msg) {
  console.error(`[bump-version] ${msg}`);
  process.exit(1);
}

function check() {
  const canonical = targets[0].read();
  if (!SEMVER.test(canonical ?? "")) {
    fail(`canonical version in ${targets[0].name} is not semver: ${canonical}`);
  }
  const mismatches = [];
  for (const t of targets) {
    const got = t.read();
    const ok = got === canonical;
    console.log(`  ${ok ? "ok  " : "DIFF"} ${t.name}: ${got}`);
    if (!ok) mismatches.push(t.name);
  }
  if (mismatches.length > 0) {
    fail(`version drift vs ${canonical}: ${mismatches.join(", ")}`);
  }
  console.log(`[bump-version] all sources agree at ${canonical}`);
}

function bump(current, level) {
  let [maj, min, pat] = current.split(".").map(Number);
  if (level === "major") [maj, min, pat] = [maj + 1, 0, 0];
  else if (level === "minor") [min, pat] = [min + 1, 0];
  else if (level === "patch") pat += 1;
  else fail(`invalid bump level: ${level}`);
  return `${maj}.${min}.${pat}`;
}

function apply(version, dryRun) {
  for (const t of targets) {
    const before = t.read();
    if (dryRun) {
      console.log(`  ${t.name}: ${before} -> ${version}${before === version ? " (no change)" : ""}`);
      continue;
    }
    t.write(version);
    console.log(`  updated ${t.name}: ${before} -> ${version}`);
  }
  console.log(`version=${version}`);
}

const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
const bumpArg = args.find((a) => a.startsWith("--bump="));
const positional = args.find((a) => !a.startsWith("--"));

if (args.includes("--check")) {
  check();
} else if (positional) {
  if (!SEMVER.test(positional)) fail(`invalid version: ${positional}`);
  apply(positional, dryRun);
} else if (bumpArg) {
  const current = targets[0].read();
  if (!SEMVER.test(current ?? "")) fail(`cannot bump non-semver version: ${current}`);
  apply(bump(current, bumpArg.slice("--bump=".length)), dryRun);
} else {
  fail("usage: bump-version.mjs <version> | --bump=<level> | --check [--dry-run]");
}
